package gildedrose

import (
	"reflect"
	"testing"
)

func Test_Foo(t *testing.T) {
	tests := []struct {
		items []*Item
		want  []*Item
	}{
		{h("+5 Dexterity Vest", -1, 0), h("+5 Dexterity Vest", -2, 0)},
		{h("+5 Dexterity Vest", -1, 1), h("+5 Dexterity Vest", -2, 0)},
		{h("+5 Dexterity Vest", -1, 2), h("+5 Dexterity Vest", -2, 0)},
		{h("+5 Dexterity Vest", -1, 3), h("+5 Dexterity Vest", -2, 1)},
		{h("+5 Dexterity Vest", -1, 4), h("+5 Dexterity Vest", -2, 2)},
		{h("+5 Dexterity Vest", -1, 5), h("+5 Dexterity Vest", -2, 3)},
		{h("+5 Dexterity Vest", -1, 46), h("+5 Dexterity Vest", -2, 44)},
		{h("+5 Dexterity Vest", -1, 47), h("+5 Dexterity Vest", -2, 45)},
		{h("+5 Dexterity Vest", -1, 48), h("+5 Dexterity Vest", -2, 46)},
		{h("+5 Dexterity Vest", -1, 49), h("+5 Dexterity Vest", -2, 47)},
		{h("+5 Dexterity Vest", -1, 50), h("+5 Dexterity Vest", -2, 48)},
		{h("+5 Dexterity Vest", 0, 0), h("+5 Dexterity Vest", -1, 0)},
		{h("+5 Dexterity Vest", 0, 1), h("+5 Dexterity Vest", -1, 0)},
		{h("+5 Dexterity Vest", 0, 2), h("+5 Dexterity Vest", -1, 0)},
		{h("+5 Dexterity Vest", 0, 3), h("+5 Dexterity Vest", -1, 1)},
		{h("+5 Dexterity Vest", 0, 4), h("+5 Dexterity Vest", -1, 2)},
		{h("+5 Dexterity Vest", 0, 5), h("+5 Dexterity Vest", -1, 3)},
		{h("+5 Dexterity Vest", 0, 46), h("+5 Dexterity Vest", -1, 44)},
		{h("+5 Dexterity Vest", 0, 47), h("+5 Dexterity Vest", -1, 45)},
		{h("+5 Dexterity Vest", 0, 48), h("+5 Dexterity Vest", -1, 46)},
		{h("+5 Dexterity Vest", 0, 49), h("+5 Dexterity Vest", -1, 47)},
		{h("+5 Dexterity Vest", 0, 50), h("+5 Dexterity Vest", -1, 48)},
		{h("+5 Dexterity Vest", 1, 0), h("+5 Dexterity Vest", 0, 0)},
		{h("+5 Dexterity Vest", 1, 1), h("+5 Dexterity Vest", 0, 0)},
		{h("+5 Dexterity Vest", 1, 2), h("+5 Dexterity Vest", 0, 1)},
		{h("+5 Dexterity Vest", 1, 3), h("+5 Dexterity Vest", 0, 2)},
		{h("+5 Dexterity Vest", 1, 4), h("+5 Dexterity Vest", 0, 3)},
		{h("+5 Dexterity Vest", 1, 5), h("+5 Dexterity Vest", 0, 4)},
		{h("+5 Dexterity Vest", 1, 46), h("+5 Dexterity Vest", 0, 45)},
		{h("+5 Dexterity Vest", 1, 47), h("+5 Dexterity Vest", 0, 46)},
		{h("+5 Dexterity Vest", 1, 48), h("+5 Dexterity Vest", 0, 47)},
		{h("+5 Dexterity Vest", 1, 49), h("+5 Dexterity Vest", 0, 48)},
		{h("+5 Dexterity Vest", 1, 50), h("+5 Dexterity Vest", 0, 49)},
		{h("+5 Dexterity Vest", 5, 0), h("+5 Dexterity Vest", 4, 0)},
		{h("+5 Dexterity Vest", 5, 1), h("+5 Dexterity Vest", 4, 0)},
		{h("+5 Dexterity Vest", 5, 2), h("+5 Dexterity Vest", 4, 1)},
		{h("+5 Dexterity Vest", 5, 3), h("+5 Dexterity Vest", 4, 2)},
		{h("+5 Dexterity Vest", 5, 4), h("+5 Dexterity Vest", 4, 3)},
		{h("+5 Dexterity Vest", 5, 5), h("+5 Dexterity Vest", 4, 4)},
		{h("+5 Dexterity Vest", 5, 46), h("+5 Dexterity Vest", 4, 45)},
		{h("+5 Dexterity Vest", 5, 47), h("+5 Dexterity Vest", 4, 46)},
		{h("+5 Dexterity Vest", 5, 48), h("+5 Dexterity Vest", 4, 47)},
		{h("+5 Dexterity Vest", 5, 49), h("+5 Dexterity Vest", 4, 48)},
		{h("+5 Dexterity Vest", 5, 50), h("+5 Dexterity Vest", 4, 49)},
		{h("+5 Dexterity Vest", 6, 0), h("+5 Dexterity Vest", 5, 0)},
		{h("+5 Dexterity Vest", 6, 1), h("+5 Dexterity Vest", 5, 0)},
		{h("+5 Dexterity Vest", 6, 2), h("+5 Dexterity Vest", 5, 1)},
		{h("+5 Dexterity Vest", 6, 3), h("+5 Dexterity Vest", 5, 2)},
		{h("+5 Dexterity Vest", 6, 4), h("+5 Dexterity Vest", 5, 3)},
		{h("+5 Dexterity Vest", 6, 5), h("+5 Dexterity Vest", 5, 4)},
		{h("+5 Dexterity Vest", 6, 46), h("+5 Dexterity Vest", 5, 45)},
		{h("+5 Dexterity Vest", 6, 47), h("+5 Dexterity Vest", 5, 46)},
		{h("+5 Dexterity Vest", 6, 48), h("+5 Dexterity Vest", 5, 47)},
		{h("+5 Dexterity Vest", 6, 49), h("+5 Dexterity Vest", 5, 48)},
		{h("+5 Dexterity Vest", 6, 50), h("+5 Dexterity Vest", 5, 49)},
		{h("+5 Dexterity Vest", 10, 0), h("+5 Dexterity Vest", 9, 0)},
		{h("+5 Dexterity Vest", 10, 1), h("+5 Dexterity Vest", 9, 0)},
		{h("+5 Dexterity Vest", 10, 2), h("+5 Dexterity Vest", 9, 1)},
		{h("+5 Dexterity Vest", 10, 3), h("+5 Dexterity Vest", 9, 2)},
		{h("+5 Dexterity Vest", 10, 4), h("+5 Dexterity Vest", 9, 3)},
		{h("+5 Dexterity Vest", 10, 5), h("+5 Dexterity Vest", 9, 4)},
		{h("+5 Dexterity Vest", 10, 46), h("+5 Dexterity Vest", 9, 45)},
		{h("+5 Dexterity Vest", 10, 47), h("+5 Dexterity Vest", 9, 46)},
		{h("+5 Dexterity Vest", 10, 48), h("+5 Dexterity Vest", 9, 47)},
		{h("+5 Dexterity Vest", 10, 49), h("+5 Dexterity Vest", 9, 48)},
		{h("+5 Dexterity Vest", 10, 50), h("+5 Dexterity Vest", 9, 49)},
		{h("+5 Dexterity Vest", 11, 0), h("+5 Dexterity Vest", 10, 0)},
		{h("+5 Dexterity Vest", 11, 1), h("+5 Dexterity Vest", 10, 0)},
		{h("+5 Dexterity Vest", 11, 2), h("+5 Dexterity Vest", 10, 1)},
		{h("+5 Dexterity Vest", 11, 3), h("+5 Dexterity Vest", 10, 2)},
		{h("+5 Dexterity Vest", 11, 4), h("+5 Dexterity Vest", 10, 3)},
		{h("+5 Dexterity Vest", 11, 5), h("+5 Dexterity Vest", 10, 4)},
		{h("+5 Dexterity Vest", 11, 46), h("+5 Dexterity Vest", 10, 45)},
		{h("+5 Dexterity Vest", 11, 47), h("+5 Dexterity Vest", 10, 46)},
		{h("+5 Dexterity Vest", 11, 48), h("+5 Dexterity Vest", 10, 47)},
		{h("+5 Dexterity Vest", 11, 49), h("+5 Dexterity Vest", 10, 48)},
		{h("+5 Dexterity Vest", 11, 50), h("+5 Dexterity Vest", 10, 49)},
		{h("+5 Dexterity Vest", 12, 0), h("+5 Dexterity Vest", 11, 0)},
		{h("+5 Dexterity Vest", 12, 1), h("+5 Dexterity Vest", 11, 0)},
		{h("+5 Dexterity Vest", 12, 2), h("+5 Dexterity Vest", 11, 1)},
		{h("+5 Dexterity Vest", 12, 3), h("+5 Dexterity Vest", 11, 2)},
		{h("+5 Dexterity Vest", 12, 4), h("+5 Dexterity Vest", 11, 3)},
		{h("+5 Dexterity Vest", 12, 5), h("+5 Dexterity Vest", 11, 4)},
		{h("+5 Dexterity Vest", 12, 46), h("+5 Dexterity Vest", 11, 45)},
		{h("+5 Dexterity Vest", 12, 47), h("+5 Dexterity Vest", 11, 46)},
		{h("+5 Dexterity Vest", 12, 48), h("+5 Dexterity Vest", 11, 47)},
		{h("+5 Dexterity Vest", 12, 49), h("+5 Dexterity Vest", 11, 48)},
		{h("+5 Dexterity Vest", 12, 50), h("+5 Dexterity Vest", 11, 49)},
		{h("Aged Brie", -1, 0), h("Aged Brie", -2, 2)},
		{h("Aged Brie", -1, 1), h("Aged Brie", -2, 3)},
		{h("Aged Brie", -1, 2), h("Aged Brie", -2, 4)},
		{h("Aged Brie", -1, 3), h("Aged Brie", -2, 5)},
		{h("Aged Brie", -1, 4), h("Aged Brie", -2, 6)},
		{h("Aged Brie", -1, 5), h("Aged Brie", -2, 7)},
		{h("Aged Brie", -1, 46), h("Aged Brie", -2, 48)},
		{h("Aged Brie", -1, 47), h("Aged Brie", -2, 49)},
		{h("Aged Brie", -1, 48), h("Aged Brie", -2, 50)},
		{h("Aged Brie", -1, 49), h("Aged Brie", -2, 50)},
		{h("Aged Brie", -1, 50), h("Aged Brie", -2, 50)},
		{h("Aged Brie", 0, 0), h("Aged Brie", -1, 2)},
		{h("Aged Brie", 0, 1), h("Aged Brie", -1, 3)},
		{h("Aged Brie", 0, 2), h("Aged Brie", -1, 4)},
		{h("Aged Brie", 0, 3), h("Aged Brie", -1, 5)},
		{h("Aged Brie", 0, 4), h("Aged Brie", -1, 6)},
		{h("Aged Brie", 0, 5), h("Aged Brie", -1, 7)},
		{h("Aged Brie", 0, 46), h("Aged Brie", -1, 48)},
		{h("Aged Brie", 0, 47), h("Aged Brie", -1, 49)},
		{h("Aged Brie", 0, 48), h("Aged Brie", -1, 50)},
		{h("Aged Brie", 0, 49), h("Aged Brie", -1, 50)},
		{h("Aged Brie", 0, 50), h("Aged Brie", -1, 50)},
		{h("Aged Brie", 1, 0), h("Aged Brie", 0, 1)},
		{h("Aged Brie", 1, 1), h("Aged Brie", 0, 2)},
		{h("Aged Brie", 1, 2), h("Aged Brie", 0, 3)},
		{h("Aged Brie", 1, 3), h("Aged Brie", 0, 4)},
		{h("Aged Brie", 1, 4), h("Aged Brie", 0, 5)},
		{h("Aged Brie", 1, 5), h("Aged Brie", 0, 6)},
		{h("Aged Brie", 1, 46), h("Aged Brie", 0, 47)},
		{h("Aged Brie", 1, 47), h("Aged Brie", 0, 48)},
		{h("Aged Brie", 1, 48), h("Aged Brie", 0, 49)},
		{h("Aged Brie", 1, 49), h("Aged Brie", 0, 50)},
		{h("Aged Brie", 1, 50), h("Aged Brie", 0, 50)},
		{h("Aged Brie", 5, 0), h("Aged Brie", 4, 1)},
		{h("Aged Brie", 5, 1), h("Aged Brie", 4, 2)},
		{h("Aged Brie", 5, 2), h("Aged Brie", 4, 3)},
		{h("Aged Brie", 5, 3), h("Aged Brie", 4, 4)},
		{h("Aged Brie", 5, 4), h("Aged Brie", 4, 5)},
		{h("Aged Brie", 5, 5), h("Aged Brie", 4, 6)},
		{h("Aged Brie", 5, 46), h("Aged Brie", 4, 47)},
		{h("Aged Brie", 5, 47), h("Aged Brie", 4, 48)},
		{h("Aged Brie", 5, 48), h("Aged Brie", 4, 49)},
		{h("Aged Brie", 5, 49), h("Aged Brie", 4, 50)},
		{h("Aged Brie", 5, 50), h("Aged Brie", 4, 50)},
		{h("Aged Brie", 6, 0), h("Aged Brie", 5, 1)},
		{h("Aged Brie", 6, 1), h("Aged Brie", 5, 2)},
		{h("Aged Brie", 6, 2), h("Aged Brie", 5, 3)},
		{h("Aged Brie", 6, 3), h("Aged Brie", 5, 4)},
		{h("Aged Brie", 6, 4), h("Aged Brie", 5, 5)},
		{h("Aged Brie", 6, 5), h("Aged Brie", 5, 6)},
		{h("Aged Brie", 6, 46), h("Aged Brie", 5, 47)},
		{h("Aged Brie", 6, 47), h("Aged Brie", 5, 48)},
		{h("Aged Brie", 6, 48), h("Aged Brie", 5, 49)},
		{h("Aged Brie", 6, 49), h("Aged Brie", 5, 50)},
		{h("Aged Brie", 6, 50), h("Aged Brie", 5, 50)},
		{h("Aged Brie", 10, 0), h("Aged Brie", 9, 1)},
		{h("Aged Brie", 10, 1), h("Aged Brie", 9, 2)},
		{h("Aged Brie", 10, 2), h("Aged Brie", 9, 3)},
		{h("Aged Brie", 10, 3), h("Aged Brie", 9, 4)},
		{h("Aged Brie", 10, 4), h("Aged Brie", 9, 5)},
		{h("Aged Brie", 10, 5), h("Aged Brie", 9, 6)},
		{h("Aged Brie", 10, 46), h("Aged Brie", 9, 47)},
		{h("Aged Brie", 10, 47), h("Aged Brie", 9, 48)},
		{h("Aged Brie", 10, 48), h("Aged Brie", 9, 49)},
		{h("Aged Brie", 10, 49), h("Aged Brie", 9, 50)},
		{h("Aged Brie", 10, 50), h("Aged Brie", 9, 50)},
		{h("Aged Brie", 11, 0), h("Aged Brie", 10, 1)},
		{h("Aged Brie", 11, 1), h("Aged Brie", 10, 2)},
		{h("Aged Brie", 11, 2), h("Aged Brie", 10, 3)},
		{h("Aged Brie", 11, 3), h("Aged Brie", 10, 4)},
		{h("Aged Brie", 11, 4), h("Aged Brie", 10, 5)},
		{h("Aged Brie", 11, 5), h("Aged Brie", 10, 6)},
		{h("Aged Brie", 11, 46), h("Aged Brie", 10, 47)},
		{h("Aged Brie", 11, 47), h("Aged Brie", 10, 48)},
		{h("Aged Brie", 11, 48), h("Aged Brie", 10, 49)},
		{h("Aged Brie", 11, 49), h("Aged Brie", 10, 50)},
		{h("Aged Brie", 11, 50), h("Aged Brie", 10, 50)},
		{h("Aged Brie", 12, 0), h("Aged Brie", 11, 1)},
		{h("Aged Brie", 12, 1), h("Aged Brie", 11, 2)},
		{h("Aged Brie", 12, 2), h("Aged Brie", 11, 3)},
		{h("Aged Brie", 12, 3), h("Aged Brie", 11, 4)},
		{h("Aged Brie", 12, 4), h("Aged Brie", 11, 5)},
		{h("Aged Brie", 12, 5), h("Aged Brie", 11, 6)},
		{h("Aged Brie", 12, 46), h("Aged Brie", 11, 47)},
		{h("Aged Brie", 12, 47), h("Aged Brie", 11, 48)},
		{h("Aged Brie", 12, 48), h("Aged Brie", 11, 49)},
		{h("Aged Brie", 12, 49), h("Aged Brie", 11, 50)},
		{h("Aged Brie", 12, 50), h("Aged Brie", 11, 50)},
		{h("Backstage passes to a TAFKAL80ETC concert", -1, 0), h("Backstage passes to a TAFKAL80ETC concert", -2, 0)},
		{h("Backstage passes to a TAFKAL80ETC concert", -1, 1), h("Backstage passes to a TAFKAL80ETC concert", -2, 0)},
		{h("Backstage passes to a TAFKAL80ETC concert", -1, 2), h("Backstage passes to a TAFKAL80ETC concert", -2, 0)},
		{h("Backstage passes to a TAFKAL80ETC concert", -1, 3), h("Backstage passes to a TAFKAL80ETC concert", -2, 0)},
		{h("Backstage passes to a TAFKAL80ETC concert", -1, 4), h("Backstage passes to a TAFKAL80ETC concert", -2, 0)},
		{h("Backstage passes to a TAFKAL80ETC concert", -1, 5), h("Backstage passes to a TAFKAL80ETC concert", -2, 0)},
		{h("Backstage passes to a TAFKAL80ETC concert", -1, 46), h("Backstage passes to a TAFKAL80ETC concert", -2, 0)},
		{h("Backstage passes to a TAFKAL80ETC concert", -1, 47), h("Backstage passes to a TAFKAL80ETC concert", -2, 0)},
		{h("Backstage passes to a TAFKAL80ETC concert", -1, 48), h("Backstage passes to a TAFKAL80ETC concert", -2, 0)},
		{h("Backstage passes to a TAFKAL80ETC concert", -1, 49), h("Backstage passes to a TAFKAL80ETC concert", -2, 0)},
		{h("Backstage passes to a TAFKAL80ETC concert", -1, 50), h("Backstage passes to a TAFKAL80ETC concert", -2, 0)},
		{h("Backstage passes to a TAFKAL80ETC concert", 0, 0), h("Backstage passes to a TAFKAL80ETC concert", -1, 0)},
		{h("Backstage passes to a TAFKAL80ETC concert", 0, 1), h("Backstage passes to a TAFKAL80ETC concert", -1, 0)},
		{h("Backstage passes to a TAFKAL80ETC concert", 0, 2), h("Backstage passes to a TAFKAL80ETC concert", -1, 0)},
		{h("Backstage passes to a TAFKAL80ETC concert", 0, 3), h("Backstage passes to a TAFKAL80ETC concert", -1, 0)},
		{h("Backstage passes to a TAFKAL80ETC concert", 0, 4), h("Backstage passes to a TAFKAL80ETC concert", -1, 0)},
		{h("Backstage passes to a TAFKAL80ETC concert", 0, 5), h("Backstage passes to a TAFKAL80ETC concert", -1, 0)},
		{h("Backstage passes to a TAFKAL80ETC concert", 0, 46), h("Backstage passes to a TAFKAL80ETC concert", -1, 0)},
		{h("Backstage passes to a TAFKAL80ETC concert", 0, 47), h("Backstage passes to a TAFKAL80ETC concert", -1, 0)},
		{h("Backstage passes to a TAFKAL80ETC concert", 0, 48), h("Backstage passes to a TAFKAL80ETC concert", -1, 0)},
		{h("Backstage passes to a TAFKAL80ETC concert", 0, 49), h("Backstage passes to a TAFKAL80ETC concert", -1, 0)},
		{h("Backstage passes to a TAFKAL80ETC concert", 0, 50), h("Backstage passes to a TAFKAL80ETC concert", -1, 0)},
		{h("Backstage passes to a TAFKAL80ETC concert", 1, 0), h("Backstage passes to a TAFKAL80ETC concert", 0, 3)},
		{h("Backstage passes to a TAFKAL80ETC concert", 1, 1), h("Backstage passes to a TAFKAL80ETC concert", 0, 4)},
		{h("Backstage passes to a TAFKAL80ETC concert", 1, 2), h("Backstage passes to a TAFKAL80ETC concert", 0, 5)},
		{h("Backstage passes to a TAFKAL80ETC concert", 1, 3), h("Backstage passes to a TAFKAL80ETC concert", 0, 6)},
		{h("Backstage passes to a TAFKAL80ETC concert", 1, 4), h("Backstage passes to a TAFKAL80ETC concert", 0, 7)},
		{h("Backstage passes to a TAFKAL80ETC concert", 1, 5), h("Backstage passes to a TAFKAL80ETC concert", 0, 8)},
		{h("Backstage passes to a TAFKAL80ETC concert", 1, 46), h("Backstage passes to a TAFKAL80ETC concert", 0, 49)},
		{h("Backstage passes to a TAFKAL80ETC concert", 1, 47), h("Backstage passes to a TAFKAL80ETC concert", 0, 50)},
		{h("Backstage passes to a TAFKAL80ETC concert", 1, 48), h("Backstage passes to a TAFKAL80ETC concert", 0, 50)},
		{h("Backstage passes to a TAFKAL80ETC concert", 1, 49), h("Backstage passes to a TAFKAL80ETC concert", 0, 50)},
		{h("Backstage passes to a TAFKAL80ETC concert", 1, 50), h("Backstage passes to a TAFKAL80ETC concert", 0, 50)},
		{h("Backstage passes to a TAFKAL80ETC concert", 5, 0), h("Backstage passes to a TAFKAL80ETC concert", 4, 3)},
		{h("Backstage passes to a TAFKAL80ETC concert", 5, 1), h("Backstage passes to a TAFKAL80ETC concert", 4, 4)},
		{h("Backstage passes to a TAFKAL80ETC concert", 5, 2), h("Backstage passes to a TAFKAL80ETC concert", 4, 5)},
		{h("Backstage passes to a TAFKAL80ETC concert", 5, 3), h("Backstage passes to a TAFKAL80ETC concert", 4, 6)},
		{h("Backstage passes to a TAFKAL80ETC concert", 5, 4), h("Backstage passes to a TAFKAL80ETC concert", 4, 7)},
		{h("Backstage passes to a TAFKAL80ETC concert", 5, 5), h("Backstage passes to a TAFKAL80ETC concert", 4, 8)},
		{h("Backstage passes to a TAFKAL80ETC concert", 5, 46), h("Backstage passes to a TAFKAL80ETC concert", 4, 49)},
		{h("Backstage passes to a TAFKAL80ETC concert", 5, 47), h("Backstage passes to a TAFKAL80ETC concert", 4, 50)},
		{h("Backstage passes to a TAFKAL80ETC concert", 5, 48), h("Backstage passes to a TAFKAL80ETC concert", 4, 50)},
		{h("Backstage passes to a TAFKAL80ETC concert", 5, 49), h("Backstage passes to a TAFKAL80ETC concert", 4, 50)},
		{h("Backstage passes to a TAFKAL80ETC concert", 5, 50), h("Backstage passes to a TAFKAL80ETC concert", 4, 50)},
		{h("Backstage passes to a TAFKAL80ETC concert", 6, 0), h("Backstage passes to a TAFKAL80ETC concert", 5, 2)},
		{h("Backstage passes to a TAFKAL80ETC concert", 6, 1), h("Backstage passes to a TAFKAL80ETC concert", 5, 3)},
		{h("Backstage passes to a TAFKAL80ETC concert", 6, 2), h("Backstage passes to a TAFKAL80ETC concert", 5, 4)},
		{h("Backstage passes to a TAFKAL80ETC concert", 6, 3), h("Backstage passes to a TAFKAL80ETC concert", 5, 5)},
		{h("Backstage passes to a TAFKAL80ETC concert", 6, 4), h("Backstage passes to a TAFKAL80ETC concert", 5, 6)},
		{h("Backstage passes to a TAFKAL80ETC concert", 6, 5), h("Backstage passes to a TAFKAL80ETC concert", 5, 7)},
		{h("Backstage passes to a TAFKAL80ETC concert", 6, 46), h("Backstage passes to a TAFKAL80ETC concert", 5, 48)},
		{h("Backstage passes to a TAFKAL80ETC concert", 6, 47), h("Backstage passes to a TAFKAL80ETC concert", 5, 49)},
		{h("Backstage passes to a TAFKAL80ETC concert", 6, 48), h("Backstage passes to a TAFKAL80ETC concert", 5, 50)},
		{h("Backstage passes to a TAFKAL80ETC concert", 6, 49), h("Backstage passes to a TAFKAL80ETC concert", 5, 50)},
		{h("Backstage passes to a TAFKAL80ETC concert", 6, 50), h("Backstage passes to a TAFKAL80ETC concert", 5, 50)},
		{h("Backstage passes to a TAFKAL80ETC concert", 10, 0), h("Backstage passes to a TAFKAL80ETC concert", 9, 2)},
		{h("Backstage passes to a TAFKAL80ETC concert", 10, 1), h("Backstage passes to a TAFKAL80ETC concert", 9, 3)},
		{h("Backstage passes to a TAFKAL80ETC concert", 10, 2), h("Backstage passes to a TAFKAL80ETC concert", 9, 4)},
		{h("Backstage passes to a TAFKAL80ETC concert", 10, 3), h("Backstage passes to a TAFKAL80ETC concert", 9, 5)},
		{h("Backstage passes to a TAFKAL80ETC concert", 10, 4), h("Backstage passes to a TAFKAL80ETC concert", 9, 6)},
		{h("Backstage passes to a TAFKAL80ETC concert", 10, 5), h("Backstage passes to a TAFKAL80ETC concert", 9, 7)},
		{h("Backstage passes to a TAFKAL80ETC concert", 10, 46), h("Backstage passes to a TAFKAL80ETC concert", 9, 48)},
		{h("Backstage passes to a TAFKAL80ETC concert", 10, 47), h("Backstage passes to a TAFKAL80ETC concert", 9, 49)},
		{h("Backstage passes to a TAFKAL80ETC concert", 10, 48), h("Backstage passes to a TAFKAL80ETC concert", 9, 50)},
		{h("Backstage passes to a TAFKAL80ETC concert", 10, 49), h("Backstage passes to a TAFKAL80ETC concert", 9, 50)},
		{h("Backstage passes to a TAFKAL80ETC concert", 10, 50), h("Backstage passes to a TAFKAL80ETC concert", 9, 50)},
		{h("Backstage passes to a TAFKAL80ETC concert", 11, 0), h("Backstage passes to a TAFKAL80ETC concert", 10, 1)},
		{h("Backstage passes to a TAFKAL80ETC concert", 11, 1), h("Backstage passes to a TAFKAL80ETC concert", 10, 2)},
		{h("Backstage passes to a TAFKAL80ETC concert", 11, 2), h("Backstage passes to a TAFKAL80ETC concert", 10, 3)},
		{h("Backstage passes to a TAFKAL80ETC concert", 11, 3), h("Backstage passes to a TAFKAL80ETC concert", 10, 4)},
		{h("Backstage passes to a TAFKAL80ETC concert", 11, 4), h("Backstage passes to a TAFKAL80ETC concert", 10, 5)},
		{h("Backstage passes to a TAFKAL80ETC concert", 11, 5), h("Backstage passes to a TAFKAL80ETC concert", 10, 6)},
		{h("Backstage passes to a TAFKAL80ETC concert", 11, 46), h("Backstage passes to a TAFKAL80ETC concert", 10, 47)},
		{h("Backstage passes to a TAFKAL80ETC concert", 11, 47), h("Backstage passes to a TAFKAL80ETC concert", 10, 48)},
		{h("Backstage passes to a TAFKAL80ETC concert", 11, 48), h("Backstage passes to a TAFKAL80ETC concert", 10, 49)},
		{h("Backstage passes to a TAFKAL80ETC concert", 11, 49), h("Backstage passes to a TAFKAL80ETC concert", 10, 50)},
		{h("Backstage passes to a TAFKAL80ETC concert", 11, 50), h("Backstage passes to a TAFKAL80ETC concert", 10, 50)},
		{h("Backstage passes to a TAFKAL80ETC concert", 12, 0), h("Backstage passes to a TAFKAL80ETC concert", 11, 1)},
		{h("Backstage passes to a TAFKAL80ETC concert", 12, 1), h("Backstage passes to a TAFKAL80ETC concert", 11, 2)},
		{h("Backstage passes to a TAFKAL80ETC concert", 12, 2), h("Backstage passes to a TAFKAL80ETC concert", 11, 3)},
		{h("Backstage passes to a TAFKAL80ETC concert", 12, 3), h("Backstage passes to a TAFKAL80ETC concert", 11, 4)},
		{h("Backstage passes to a TAFKAL80ETC concert", 12, 4), h("Backstage passes to a TAFKAL80ETC concert", 11, 5)},
		{h("Backstage passes to a TAFKAL80ETC concert", 12, 5), h("Backstage passes to a TAFKAL80ETC concert", 11, 6)},
		{h("Backstage passes to a TAFKAL80ETC concert", 12, 46), h("Backstage passes to a TAFKAL80ETC concert", 11, 47)},
		{h("Backstage passes to a TAFKAL80ETC concert", 12, 47), h("Backstage passes to a TAFKAL80ETC concert", 11, 48)},
		{h("Backstage passes to a TAFKAL80ETC concert", 12, 48), h("Backstage passes to a TAFKAL80ETC concert", 11, 49)},
		{h("Backstage passes to a TAFKAL80ETC concert", 12, 49), h("Backstage passes to a TAFKAL80ETC concert", 11, 50)},
		{h("Backstage passes to a TAFKAL80ETC concert", 12, 50), h("Backstage passes to a TAFKAL80ETC concert", 11, 50)},
		{h("Sulfuras, Hand of Ragnaros", -1, 0), h("Sulfuras, Hand of Ragnaros", -1, 0)},
		{h("Sulfuras, Hand of Ragnaros", -1, 1), h("Sulfuras, Hand of Ragnaros", -1, 1)},
		{h("Sulfuras, Hand of Ragnaros", -1, 2), h("Sulfuras, Hand of Ragnaros", -1, 2)},
		{h("Sulfuras, Hand of Ragnaros", -1, 3), h("Sulfuras, Hand of Ragnaros", -1, 3)},
		{h("Sulfuras, Hand of Ragnaros", -1, 4), h("Sulfuras, Hand of Ragnaros", -1, 4)},
		{h("Sulfuras, Hand of Ragnaros", -1, 5), h("Sulfuras, Hand of Ragnaros", -1, 5)},
		{h("Sulfuras, Hand of Ragnaros", -1, 46), h("Sulfuras, Hand of Ragnaros", -1, 46)},
		{h("Sulfuras, Hand of Ragnaros", -1, 47), h("Sulfuras, Hand of Ragnaros", -1, 47)},
		{h("Sulfuras, Hand of Ragnaros", -1, 48), h("Sulfuras, Hand of Ragnaros", -1, 48)},
		{h("Sulfuras, Hand of Ragnaros", -1, 49), h("Sulfuras, Hand of Ragnaros", -1, 49)},
		{h("Sulfuras, Hand of Ragnaros", -1, 50), h("Sulfuras, Hand of Ragnaros", -1, 50)},
		{h("Sulfuras, Hand of Ragnaros", 0, 0), h("Sulfuras, Hand of Ragnaros", 0, 0)},
		{h("Sulfuras, Hand of Ragnaros", 0, 1), h("Sulfuras, Hand of Ragnaros", 0, 1)},
		{h("Sulfuras, Hand of Ragnaros", 0, 2), h("Sulfuras, Hand of Ragnaros", 0, 2)},
		{h("Sulfuras, Hand of Ragnaros", 0, 3), h("Sulfuras, Hand of Ragnaros", 0, 3)},
		{h("Sulfuras, Hand of Ragnaros", 0, 4), h("Sulfuras, Hand of Ragnaros", 0, 4)},
		{h("Sulfuras, Hand of Ragnaros", 0, 5), h("Sulfuras, Hand of Ragnaros", 0, 5)},
		{h("Sulfuras, Hand of Ragnaros", 0, 46), h("Sulfuras, Hand of Ragnaros", 0, 46)},
		{h("Sulfuras, Hand of Ragnaros", 0, 47), h("Sulfuras, Hand of Ragnaros", 0, 47)},
		{h("Sulfuras, Hand of Ragnaros", 0, 48), h("Sulfuras, Hand of Ragnaros", 0, 48)},
		{h("Sulfuras, Hand of Ragnaros", 0, 49), h("Sulfuras, Hand of Ragnaros", 0, 49)},
		{h("Sulfuras, Hand of Ragnaros", 0, 50), h("Sulfuras, Hand of Ragnaros", 0, 50)},
		{h("Sulfuras, Hand of Ragnaros", 1, 0), h("Sulfuras, Hand of Ragnaros", 1, 0)},
		{h("Sulfuras, Hand of Ragnaros", 1, 1), h("Sulfuras, Hand of Ragnaros", 1, 1)},
		{h("Sulfuras, Hand of Ragnaros", 1, 2), h("Sulfuras, Hand of Ragnaros", 1, 2)},
		{h("Sulfuras, Hand of Ragnaros", 1, 3), h("Sulfuras, Hand of Ragnaros", 1, 3)},
		{h("Sulfuras, Hand of Ragnaros", 1, 4), h("Sulfuras, Hand of Ragnaros", 1, 4)},
		{h("Sulfuras, Hand of Ragnaros", 1, 5), h("Sulfuras, Hand of Ragnaros", 1, 5)},
		{h("Sulfuras, Hand of Ragnaros", 1, 46), h("Sulfuras, Hand of Ragnaros", 1, 46)},
		{h("Sulfuras, Hand of Ragnaros", 1, 47), h("Sulfuras, Hand of Ragnaros", 1, 47)},
		{h("Sulfuras, Hand of Ragnaros", 1, 48), h("Sulfuras, Hand of Ragnaros", 1, 48)},
		{h("Sulfuras, Hand of Ragnaros", 1, 49), h("Sulfuras, Hand of Ragnaros", 1, 49)},
		{h("Sulfuras, Hand of Ragnaros", 1, 50), h("Sulfuras, Hand of Ragnaros", 1, 50)},
		{h("Sulfuras, Hand of Ragnaros", 5, 0), h("Sulfuras, Hand of Ragnaros", 5, 0)},
		{h("Sulfuras, Hand of Ragnaros", 5, 1), h("Sulfuras, Hand of Ragnaros", 5, 1)},
		{h("Sulfuras, Hand of Ragnaros", 5, 2), h("Sulfuras, Hand of Ragnaros", 5, 2)},
		{h("Sulfuras, Hand of Ragnaros", 5, 3), h("Sulfuras, Hand of Ragnaros", 5, 3)},
		{h("Sulfuras, Hand of Ragnaros", 5, 4), h("Sulfuras, Hand of Ragnaros", 5, 4)},
		{h("Sulfuras, Hand of Ragnaros", 5, 5), h("Sulfuras, Hand of Ragnaros", 5, 5)},
		{h("Sulfuras, Hand of Ragnaros", 5, 46), h("Sulfuras, Hand of Ragnaros", 5, 46)},
		{h("Sulfuras, Hand of Ragnaros", 5, 47), h("Sulfuras, Hand of Ragnaros", 5, 47)},
		{h("Sulfuras, Hand of Ragnaros", 5, 48), h("Sulfuras, Hand of Ragnaros", 5, 48)},
		{h("Sulfuras, Hand of Ragnaros", 5, 49), h("Sulfuras, Hand of Ragnaros", 5, 49)},
		{h("Sulfuras, Hand of Ragnaros", 5, 50), h("Sulfuras, Hand of Ragnaros", 5, 50)},
		{h("Sulfuras, Hand of Ragnaros", 6, 0), h("Sulfuras, Hand of Ragnaros", 6, 0)},
		{h("Sulfuras, Hand of Ragnaros", 6, 1), h("Sulfuras, Hand of Ragnaros", 6, 1)},
		{h("Sulfuras, Hand of Ragnaros", 6, 2), h("Sulfuras, Hand of Ragnaros", 6, 2)},
		{h("Sulfuras, Hand of Ragnaros", 6, 3), h("Sulfuras, Hand of Ragnaros", 6, 3)},
		{h("Sulfuras, Hand of Ragnaros", 6, 4), h("Sulfuras, Hand of Ragnaros", 6, 4)},
		{h("Sulfuras, Hand of Ragnaros", 6, 5), h("Sulfuras, Hand of Ragnaros", 6, 5)},
		{h("Sulfuras, Hand of Ragnaros", 6, 46), h("Sulfuras, Hand of Ragnaros", 6, 46)},
		{h("Sulfuras, Hand of Ragnaros", 6, 47), h("Sulfuras, Hand of Ragnaros", 6, 47)},
		{h("Sulfuras, Hand of Ragnaros", 6, 48), h("Sulfuras, Hand of Ragnaros", 6, 48)},
		{h("Sulfuras, Hand of Ragnaros", 6, 49), h("Sulfuras, Hand of Ragnaros", 6, 49)},
		{h("Sulfuras, Hand of Ragnaros", 6, 50), h("Sulfuras, Hand of Ragnaros", 6, 50)},
		{h("Sulfuras, Hand of Ragnaros", 10, 0), h("Sulfuras, Hand of Ragnaros", 10, 0)},
		{h("Sulfuras, Hand of Ragnaros", 10, 1), h("Sulfuras, Hand of Ragnaros", 10, 1)},
		{h("Sulfuras, Hand of Ragnaros", 10, 2), h("Sulfuras, Hand of Ragnaros", 10, 2)},
		{h("Sulfuras, Hand of Ragnaros", 10, 3), h("Sulfuras, Hand of Ragnaros", 10, 3)},
		{h("Sulfuras, Hand of Ragnaros", 10, 4), h("Sulfuras, Hand of Ragnaros", 10, 4)},
		{h("Sulfuras, Hand of Ragnaros", 10, 5), h("Sulfuras, Hand of Ragnaros", 10, 5)},
		{h("Sulfuras, Hand of Ragnaros", 10, 46), h("Sulfuras, Hand of Ragnaros", 10, 46)},
		{h("Sulfuras, Hand of Ragnaros", 10, 47), h("Sulfuras, Hand of Ragnaros", 10, 47)},
		{h("Sulfuras, Hand of Ragnaros", 10, 48), h("Sulfuras, Hand of Ragnaros", 10, 48)},
		{h("Sulfuras, Hand of Ragnaros", 10, 49), h("Sulfuras, Hand of Ragnaros", 10, 49)},
		{h("Sulfuras, Hand of Ragnaros", 10, 50), h("Sulfuras, Hand of Ragnaros", 10, 50)},
		{h("Sulfuras, Hand of Ragnaros", 11, 0), h("Sulfuras, Hand of Ragnaros", 11, 0)},
		{h("Sulfuras, Hand of Ragnaros", 11, 1), h("Sulfuras, Hand of Ragnaros", 11, 1)},
		{h("Sulfuras, Hand of Ragnaros", 11, 2), h("Sulfuras, Hand of Ragnaros", 11, 2)},
		{h("Sulfuras, Hand of Ragnaros", 11, 3), h("Sulfuras, Hand of Ragnaros", 11, 3)},
		{h("Sulfuras, Hand of Ragnaros", 11, 4), h("Sulfuras, Hand of Ragnaros", 11, 4)},
		{h("Sulfuras, Hand of Ragnaros", 11, 5), h("Sulfuras, Hand of Ragnaros", 11, 5)},
		{h("Sulfuras, Hand of Ragnaros", 11, 46), h("Sulfuras, Hand of Ragnaros", 11, 46)},
		{h("Sulfuras, Hand of Ragnaros", 11, 47), h("Sulfuras, Hand of Ragnaros", 11, 47)},
		{h("Sulfuras, Hand of Ragnaros", 11, 48), h("Sulfuras, Hand of Ragnaros", 11, 48)},
		{h("Sulfuras, Hand of Ragnaros", 11, 49), h("Sulfuras, Hand of Ragnaros", 11, 49)},
		{h("Sulfuras, Hand of Ragnaros", 11, 50), h("Sulfuras, Hand of Ragnaros", 11, 50)},
		{h("Sulfuras, Hand of Ragnaros", 12, 0), h("Sulfuras, Hand of Ragnaros", 12, 0)},
		{h("Sulfuras, Hand of Ragnaros", 12, 1), h("Sulfuras, Hand of Ragnaros", 12, 1)},
		{h("Sulfuras, Hand of Ragnaros", 12, 2), h("Sulfuras, Hand of Ragnaros", 12, 2)},
		{h("Sulfuras, Hand of Ragnaros", 12, 3), h("Sulfuras, Hand of Ragnaros", 12, 3)},
		{h("Sulfuras, Hand of Ragnaros", 12, 4), h("Sulfuras, Hand of Ragnaros", 12, 4)},
		{h("Sulfuras, Hand of Ragnaros", 12, 5), h("Sulfuras, Hand of Ragnaros", 12, 5)},
		{h("Sulfuras, Hand of Ragnaros", 12, 46), h("Sulfuras, Hand of Ragnaros", 12, 46)},
		{h("Sulfuras, Hand of Ragnaros", 12, 47), h("Sulfuras, Hand of Ragnaros", 12, 47)},
		{h("Sulfuras, Hand of Ragnaros", 12, 48), h("Sulfuras, Hand of Ragnaros", 12, 48)},
		{h("Sulfuras, Hand of Ragnaros", 12, 49), h("Sulfuras, Hand of Ragnaros", 12, 49)},
		{h("Sulfuras, Hand of Ragnaros", 12, 50), h("Sulfuras, Hand of Ragnaros", 12, 50)},
		{h("Conjured Mana Cake", -1, 0), h("Conjured Mana Cake", -2, 0)},
		{h("Conjured Mana Cake", -1, 1), h("Conjured Mana Cake", -2, 0)},
		{h("Conjured Mana Cake", -1, 2), h("Conjured Mana Cake", -2, 0)},
		{h("Conjured Mana Cake", -1, 3), h("Conjured Mana Cake", -2, 0)},
		{h("Conjured Mana Cake", -1, 4), h("Conjured Mana Cake", -2, 0)},
		{h("Conjured Mana Cake", -1, 5), h("Conjured Mana Cake", -2, 1)},
		{h("Conjured Mana Cake", -1, 46), h("Conjured Mana Cake", -2, 42)},
		{h("Conjured Mana Cake", -1, 47), h("Conjured Mana Cake", -2, 43)},
		{h("Conjured Mana Cake", -1, 48), h("Conjured Mana Cake", -2, 44)},
		{h("Conjured Mana Cake", -1, 49), h("Conjured Mana Cake", -2, 45)},
		{h("Conjured Mana Cake", -1, 50), h("Conjured Mana Cake", -2, 46)},
		{h("Conjured Mana Cake", 0, 0), h("Conjured Mana Cake", -1, 0)},
		{h("Conjured Mana Cake", 0, 1), h("Conjured Mana Cake", -1, 0)},
		{h("Conjured Mana Cake", 0, 2), h("Conjured Mana Cake", -1, 0)},
		{h("Conjured Mana Cake", 0, 3), h("Conjured Mana Cake", -1, 0)},
		{h("Conjured Mana Cake", 0, 4), h("Conjured Mana Cake", -1, 0)},
		{h("Conjured Mana Cake", 0, 5), h("Conjured Mana Cake", -1, 1)},
		{h("Conjured Mana Cake", 0, 46), h("Conjured Mana Cake", -1, 42)},
		{h("Conjured Mana Cake", 0, 47), h("Conjured Mana Cake", -1, 43)},
		{h("Conjured Mana Cake", 0, 48), h("Conjured Mana Cake", -1, 44)},
		{h("Conjured Mana Cake", 0, 49), h("Conjured Mana Cake", -1, 45)},
		{h("Conjured Mana Cake", 0, 50), h("Conjured Mana Cake", -1, 46)},
		{h("Conjured Mana Cake", 1, 0), h("Conjured Mana Cake", 0, 0)},
		{h("Conjured Mana Cake", 1, 1), h("Conjured Mana Cake", 0, 0)},
		{h("Conjured Mana Cake", 1, 2), h("Conjured Mana Cake", 0, 0)},
		{h("Conjured Mana Cake", 1, 3), h("Conjured Mana Cake", 0, 1)},
		{h("Conjured Mana Cake", 1, 4), h("Conjured Mana Cake", 0, 2)},
		{h("Conjured Mana Cake", 1, 5), h("Conjured Mana Cake", 0, 3)},
		{h("Conjured Mana Cake", 1, 46), h("Conjured Mana Cake", 0, 44)},
		{h("Conjured Mana Cake", 1, 47), h("Conjured Mana Cake", 0, 45)},
		{h("Conjured Mana Cake", 1, 48), h("Conjured Mana Cake", 0, 46)},
		{h("Conjured Mana Cake", 1, 49), h("Conjured Mana Cake", 0, 47)},
		{h("Conjured Mana Cake", 1, 50), h("Conjured Mana Cake", 0, 48)},
		{h("Conjured Mana Cake", 5, 0), h("Conjured Mana Cake", 4, 0)},
		{h("Conjured Mana Cake", 5, 1), h("Conjured Mana Cake", 4, 0)},
		{h("Conjured Mana Cake", 5, 2), h("Conjured Mana Cake", 4, 0)},
		{h("Conjured Mana Cake", 5, 3), h("Conjured Mana Cake", 4, 1)},
		{h("Conjured Mana Cake", 5, 4), h("Conjured Mana Cake", 4, 2)},
		{h("Conjured Mana Cake", 5, 5), h("Conjured Mana Cake", 4, 3)},
		{h("Conjured Mana Cake", 5, 46), h("Conjured Mana Cake", 4, 44)},
		{h("Conjured Mana Cake", 5, 47), h("Conjured Mana Cake", 4, 45)},
		{h("Conjured Mana Cake", 5, 48), h("Conjured Mana Cake", 4, 46)},
		{h("Conjured Mana Cake", 5, 49), h("Conjured Mana Cake", 4, 47)},
		{h("Conjured Mana Cake", 5, 50), h("Conjured Mana Cake", 4, 48)},
		{h("Conjured Mana Cake", 6, 0), h("Conjured Mana Cake", 5, 0)},
		{h("Conjured Mana Cake", 6, 1), h("Conjured Mana Cake", 5, 0)},
		{h("Conjured Mana Cake", 6, 2), h("Conjured Mana Cake", 5, 0)},
		{h("Conjured Mana Cake", 6, 3), h("Conjured Mana Cake", 5, 1)},
		{h("Conjured Mana Cake", 6, 4), h("Conjured Mana Cake", 5, 2)},
		{h("Conjured Mana Cake", 6, 5), h("Conjured Mana Cake", 5, 3)},
		{h("Conjured Mana Cake", 6, 46), h("Conjured Mana Cake", 5, 44)},
		{h("Conjured Mana Cake", 6, 47), h("Conjured Mana Cake", 5, 45)},
		{h("Conjured Mana Cake", 6, 48), h("Conjured Mana Cake", 5, 46)},
		{h("Conjured Mana Cake", 6, 49), h("Conjured Mana Cake", 5, 47)},
		{h("Conjured Mana Cake", 6, 50), h("Conjured Mana Cake", 5, 48)},
		{h("Conjured Mana Cake", 10, 0), h("Conjured Mana Cake", 9, 0)},
		{h("Conjured Mana Cake", 10, 1), h("Conjured Mana Cake", 9, 0)},
		{h("Conjured Mana Cake", 10, 2), h("Conjured Mana Cake", 9, 0)},
		{h("Conjured Mana Cake", 10, 3), h("Conjured Mana Cake", 9, 1)},
		{h("Conjured Mana Cake", 10, 4), h("Conjured Mana Cake", 9, 2)},
		{h("Conjured Mana Cake", 10, 5), h("Conjured Mana Cake", 9, 3)},
		{h("Conjured Mana Cake", 10, 46), h("Conjured Mana Cake", 9, 44)},
		{h("Conjured Mana Cake", 10, 47), h("Conjured Mana Cake", 9, 45)},
		{h("Conjured Mana Cake", 10, 48), h("Conjured Mana Cake", 9, 46)},
		{h("Conjured Mana Cake", 10, 49), h("Conjured Mana Cake", 9, 47)},
		{h("Conjured Mana Cake", 10, 50), h("Conjured Mana Cake", 9, 48)},
		{h("Conjured Mana Cake", 11, 0), h("Conjured Mana Cake", 10, 0)},
		{h("Conjured Mana Cake", 11, 1), h("Conjured Mana Cake", 10, 0)},
		{h("Conjured Mana Cake", 11, 2), h("Conjured Mana Cake", 10, 0)},
		{h("Conjured Mana Cake", 11, 3), h("Conjured Mana Cake", 10, 1)},
		{h("Conjured Mana Cake", 11, 4), h("Conjured Mana Cake", 10, 2)},
		{h("Conjured Mana Cake", 11, 5), h("Conjured Mana Cake", 10, 3)},
		{h("Conjured Mana Cake", 11, 46), h("Conjured Mana Cake", 10, 44)},
		{h("Conjured Mana Cake", 11, 47), h("Conjured Mana Cake", 10, 45)},
		{h("Conjured Mana Cake", 11, 48), h("Conjured Mana Cake", 10, 46)},
		{h("Conjured Mana Cake", 11, 49), h("Conjured Mana Cake", 10, 47)},
		{h("Conjured Mana Cake", 11, 50), h("Conjured Mana Cake", 10, 48)},
		{h("Conjured Mana Cake", 12, 0), h("Conjured Mana Cake", 11, 0)},
		{h("Conjured Mana Cake", 12, 1), h("Conjured Mana Cake", 11, 0)},
		{h("Conjured Mana Cake", 12, 2), h("Conjured Mana Cake", 11, 0)},
		{h("Conjured Mana Cake", 12, 3), h("Conjured Mana Cake", 11, 1)},
		{h("Conjured Mana Cake", 12, 4), h("Conjured Mana Cake", 11, 2)},
		{h("Conjured Mana Cake", 12, 5), h("Conjured Mana Cake", 11, 3)},
		{h("Conjured Mana Cake", 12, 46), h("Conjured Mana Cake", 11, 44)},
		{h("Conjured Mana Cake", 12, 47), h("Conjured Mana Cake", 11, 45)},
		{h("Conjured Mana Cake", 12, 48), h("Conjured Mana Cake", 11, 46)},
		{h("Conjured Mana Cake", 12, 49), h("Conjured Mana Cake", 11, 47)},
		{h("Conjured Mana Cake", 12, 50), h("Conjured Mana Cake", 11, 48)},
	}

	for _, testCase := range tests {
		t.Run("case", func(t *testing.T) {
			UpdateQuality(testCase.items)
			if len(testCase.items) != len(testCase.want) {
				t.Log(testCase.items)
				t.Log(testCase.want)
				t.Fatal("unequal length")
			}

			for i := range testCase.items {
				if !reflect.DeepEqual(*testCase.items[i], *testCase.want[i]) {
					t.Log(testCase.items[i])
					t.Log(testCase.want[i])
					t.Error("unequal item")
				}
			}
		})
	}
}

func h(name string, sellIn, quality int) []*Item {
	return []*Item{{name, sellIn, quality}}
}
